"""новая миграция

Revision ID: 41d7bac183e0
Revises: 
Create Date: 2025-05-15 05:46:51.457922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d7bac183e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coworking', 'coworking_location',
                existing_type=sa.VARCHAR(length=100),
                type_=sa.Integer(),
                postgresql_using='coworking_location::integer',
                existing_nullable=False)
    op.drop_column('coworking', 'coworking_description')
    op.add_column('event', sa.Column('event_photo', sa.String(length=255), nullable=False))
    op.add_column('event', sa.Column('event_host', sa.String(length=255), nullable=False))
    op.add_column('event', sa.Column('event_price', sa.String(length=10), nullable=False))
    op.add_column('news', sa.Column('news_photo', sa.String(length=255), nullable=False))
    op.add_column('news', sa.Column('news_title', sa.String(length=50), nullable=False))
    op.drop_column('news', 'news_image')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('news_image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('news', 'news_title')
    op.drop_column('news', 'news_photo')
    op.drop_column('event', 'event_price')
    op.drop_column('event', 'event_host')
    op.drop_column('event', 'event_photo')
    op.add_column('coworking', sa.Column('coworking_description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('coworking', 'coworking_location',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
