"""add_coworking_descriptio

Revision ID: 87aa363b6e82
Revises: c006c3dd8928
Create Date: 2025-05-18 10:41:40.913820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aa363b6e82'
down_revision: Union[str, None] = 'c006c3dd8928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coworking', sa.Column('coworking_description', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coworking', 'coworking_description')
    # ### end Alembic commands ###
