"""add_coworking_description

Revision ID: c006c3dd8928
Revises: 6fc9b1d0354a
Create Date: 2025-05-18 10:38:20.006375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c006c3dd8928'
down_revision: Union[str, None] = '6fc9b1d0354a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
